//
//  URLMethods.swift
//  Lion Miles
//
//  Created by Arkmacbook on 22/10/20.
//

import UIKit
let historyNotification = "GetPushHistoryDetails"
let customerType_URLMethodName = "GetAttributeDetails"
let membershipExistancy_URLMethod = "CheckCustomerExistancyAndVerification"
let loginSubmission_URLMethod = "CheckIsAuthenticatedMobileApp"
let otp_URLMethod = "SaveAndGetOTPDetails"

let stateList_URLMethod = "GetStateDetailsMobileApp"
let districtList_URLMethod = "GetDistrictDetails"
let talukList_URLMethod = "GetTalukDetails"
let registrationSubmission_URLMethod = "SaveCustomerRegistrationDetailsMobileApp"
let forgetPassword_URLMethod = "CheckIsAuthenticatedMobileApp"
let dashboard_URLMethod = "GetDashBoardDetailsApi"
let dashboardBanner_URLMethod = "BindLandingImageList"
let profileImageUpload_URLMethod = "UpdateCustomerProfileMobileApp"
let profileDetails_URLMethod = "GetCustomerDetailsMobileApp"
let claimPurchaseNameList_URLMethod = "GetCustParentChildMappingDetails"
let enrollmentList_URLMethod = "GetCustParentChildMappingDetails"
let claimPurchaseSubmission_URLMethod = "SavePurchaseRequest"
let myPurchaseClaimList_URLMethod = "BindAssessmentRequestDetails"
let getWorkSiteDetails_URLMethod = "GetWorkSiteDetails"
let saveWorkSiteInfo_URLMethod = "SaveWorkSiteInfo"
let productCategory_URLMethod = "GetCatalogueCategoryDetails"
let productCatalogue_URLMethod = "GetCatalogueDetails"
let productAddToCart_URLMethod = "SaveCatalogueCartDetailsMobile"
let productMyCartList_URLMethod = "GetCatalogueCartDetailsMobile"
let productPlannerList_URLMethod = "GetRedemptionPlannerDetails"
let productAddToPlanner_URLMethod = "GetCatalogueDetails"
let myCartUpdate_URLMethod = "UpdateCustomerCart"
let plannerRemove_URLMethod = "GetPlannerAddedOrNot"
let redemptionSubmissionURLmethod = "SaveCatalogueRedemptionDetails"
let sendSMStoUser = "SendSMSForSuccessfulRedemptionMobileApp"
let userStatusUrlMethod = "UserActiveOrInActive"
let myRedemptionListURLMethod = "GetCatalogueDetails"

let pendingClaimURLMethod = "GetPurchaseRequestDetailsList"
let pendingClaimSubmission = "SaveApprovePurchaseRequestDetail"
let claimHistoryURLMethod = "BindAssessmentRequestDetails"
let supportExecutive = "GetCustParentChildMappingDetails"
let newSupportExecutive = "SaveCustomerRegistrationDetailsMobileApp"
let deactivateSupportExecutive = "CustomerAccountDelete"
let queryListURLMethod = "SaveCustomerQueryTicket"
let queryTopicURLMethod = "GetHelpTopics"

let getCashTransferDenominations = "GetCashTransferDenominations"
let newQuerySubmissionURLMethod = "SaveCustomerQueryTicket"
let chatDetails_URLMethod = "GetQueryResponseInformation"
let newChatSubmit_URLMethod = "SaveCustomerQueryTicket"
let myEarningList_URLMethod = "GetRewardTransactionDetailsMobileApp"

let tcMethodname = "SaveOrGetTermAndConditions"
let profileUpdate_URLMethod = "SaveCustomerDetails"
let referandEarnURLMethod = "SaveReferralDetails"
let deactivatedAccount_URLMethod = "SaveCustomerDetails"
let activateSubmission_URLMethod = "SaveCustomerDetails"
let getAccountDetails = "GetCustomerDetailsMobileApp"
let city_URLMethod = "GetCityDetails"
let offersandPromotions_URLMethod = "GetPromotionDetailsMobileApp"
let myDreamGiftList_URLMethod = "GetDreamGiftDetails"
let removeDreamGift_URLMethod = "SaveOrUpdateDreamGiftDetails"
let preferredLanguage_URLMethod = "GetAttributeDetails"
let evoucherList_MethodName = "GetCatalogueDetails"
let voucherRedeem_URLMethodName = "SaveCatalogueRedemptionDetailsEssilor"
let voucherList_URLMethod = "GetCatalogueDetails"
let voucherFixedpoints_URLMethod = "GetCatalogueDetails"
let voucherSubmit_URLMethod = "SaveCatalogueRedemptionDetails"

let saveCustomerCasTransferDEtails = "SaveCustomerCasTransferDEtails"

let cashTransferHistoryList = "GetCustomerCashTransferList"
let cashTransferApproveOrRejectionSubmission = "CustomerCashTransferApprovalOrRejection"
let myredemptionDetails_URLMethodName = "GetCustomerRedemptionHistorydetails"
let getProductDetails_URLMethodName = "GetProductDetails"

